[package]
name = "pattern-match"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = "1.1.3"
hex-literal = "0.4.1"
kmp = "0.1.1"
pattern-match-macros = { version = "0.1.0", path = "../pattern-match-macros" }

[profile.release]
opt-level = 3
lto = true
